dist: trusty
sudo: false
language: python
python:
  - '2.7'


# Cache the .mbs folder and ant libraries.
cache:
  directories:
    - $HOME/.mbs
    - $HOME/.ant/lib


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - python2.7 mbs/mbs
