language: python
python:
  - '2.7'


# Use the new container-based infrastructure. No "sudo" is possible now.
sudo: false


# Cache the .mbs folder and ant libraries.
cache:
  directories:
    - $HOME/.mbs
    - $HOME/.ant/lib


env:
  - secure: iM2+K5JO3JVBwLwe+fwMOvRNvKPJOOFeJ+kw1YwGyQs8o/89Mgt4wnBxJX3Bkazdwxh+3GYsF87ZI29Nts9RHmM3Wj8eW9/xvjvdiGa/qVKzMSxOvfuYingofD72qD+mEpUQK2qDUSrNSCFMmY84xypbhUri5Y2PGc9j+GoTBJU=


install:
  - pip install -q requests


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - python mbs/mbs


# Deploy the artifacts to Bintray.
after_success:
  - python ivy/deploy.py targets/artifacts.xml


# Deploy the artifacts to GitHub.
deploy:
  provider: releases
  api_key:
    secure: WAtMuy9fjMrpKZKjZQoqkB6jHlVViX1/RVuLvXp1C8d+e45IS4P+GiS+qxs9NOm8z2jDU2nh6lC8FvwmaOw1gMKUkO94BC+isYbvSa2b5CyH7a7ceLiEaRgVCVrVWc+S07rUkUKf+7WqlX/NMS8x7FJcbU3S19MDBEw8q/xEGho=
  file:
    - targets/ivy/ivy.xml
    - targets/ivy/muhkuh_tester_cli.zip
  skip_cleanup: true
  on:
    repo: muhkuh-sys/org.muhkuh.tools-muhkuh_tester_cli
    tags: true
